### ISSUE TITLE
Request for notification of new releases and updates

### ISSUE THREAD

**Issue by Coolie2** [DrUm78/scummvm#1]
Hey DrUm, it's Coolie; I was wondering if perhaps you could notify me somehow when you release an updated version of one of your FunKey OPKs or release a new one so that I may make the necessary modification(s) to the OPK page of the wiki? I've now uploaded all the updated versions you've released recently and added all the missing repository links, but this process might be simpler if I knew exactly what was being updated when. If you're willing to do so, I've sent you a friend request on Discord if you'd like to update me there. You could otherwise reply here each time and I could check just this page every so often or email me at the email address listed in the "About" section of my YouTube channel.

Otherwise, you've been missed on the Discord server, but it's not our business why anyone decides to leave; just feel free to return whenever you'd like!

**Comment by DrUm78** [comment]
I often update ScummVM from the official source repo. Stable 2.3.0 is not out yet so they are daily builds, no need to get the last one everyday, just watch the changelog in the "Releases" section. To be notified about my updates, you should simply use the "Watch" (individual repo) or "Follow" (my account) functions of github I guess.
